### ISSUE TITLE
[Feature]더하기 모듈

### ISSUE THREAD

**Issue by always0ne** [SPLUG-GIT/project#2]
## 추가해야 하는 기능 에 대한 간단한 설명
사칙연산 계산기에 사용될 더하기 모듈

## 기능이 왜 필요한지
사칙연산 계산기를 만들기 위해서는 모듈화된 덧셈기능이 필요하다

## 어떻게 구현해야 하는지
매개변수 2개를 받아 두 값을 더한 값을 리턴한다.
정수만 입력받았을 때는 정수를 리턴, 실수를 포함했을때는 실수를 리턴해야 한다.

@DAEHOCHANG

**Comment by DAEHOCHANG** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by yesterdayKite** [comment]
사칙연산 싫어요 ~.~  
![Uploading 딥러닝플로차트.png…]()
